[package]
name = "lok"
version = "0.0.5"
edition = "2018"

authors = ["wyhaya <wyhaya@gmail.com>"]
description = "Calculation code information"
homepage = "https://github.com/wyhaya/lok"
repository = "https://github.com/wyhaya/lok.git"
license = "MIT"
readme = "README.md"

keywords = [
    "codes",
    "count",
    "count-lines-of-code",
    "command-line-tool"
]

[dependencies]
ace = "0.0.2"
bright = "0.2.0"
crossbeam-deque = "0.7.2"
lazy_static = "1.4.0"
num_cpus = "1.11.1"
regex = "1.3.1"
walkdir = "2.2.9"
